### ISSUE TITLE
As a user I can see the cascading events when triggering an event

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/vscode-stripe#121]
When triggering an event with cascading events, such as `payment_method.attach` (first fires off a `customer.created` event) it would be great to see the cascading events as nested under the event I actually triggered (or visually subordinate).

```
- payment_method.attached
-   - customer.created
```

**Comment by gracegoo-stripe** [comment]
Hey Kenneth, we are updating the "Recent Events" view to display a stream of events coming in instead of grabbing all events for the merchant from the CLI. We want the experience to be similar to the log streaming view we have. Closing this out for now but please re-open this if you have other comments or concerns!
