### ISSUE TITLE
Survey Prompt Improvements

### ISSUE THREAD

**Issue by gracegoo-stripe** [stripe/vscode-stripe#145]
Some suggestions for improvements to our prompt:
1. Instead of a 12 week timeout on the prompt from when the user last took the survey, we should persist the version of the survey they took and compare that to the on we are about to prompt them to take. 
2. If the user opens the survey on their own through the `Help and Feedback` section, we should also persist that in context so that we don't prompt them to take the survey again.

**Comment by jbyrum-stripe** [comment]
Direct feedback from user: 

"I answered to the survey the next day after I installed the extension, and I was pretty happy with it, but now it is constantly asking me to participate in this exact same feedback survey. I get a notification on more than one window, and notifications also appear while I am doing work after having closed them. It is very disturbing, and obviously questions did not change between few days ago when I answered the survey and now. I don't want to turn off the notifications because I like helping with feedback surveys from time to time, but the notification spam for this survey is making me lean towards disabling them..."

**Comment by gracegoo-stripe** [comment]
#1 was addressed by https://github.com/stripe/vscode-stripe/pull/212
#2 was addressed by https://github.com/stripe/vscode-stripe/pull/213

The feedback from the user was fixed in this commit: https://github.com/stripe/vscode-stripe/commit/f18a4a2ba4acea6f07a37ddb4563d4078ae1a73e
