### ISSUE TITLE
Show log entry inside the editor

### ISSUE THREAD

**Issue by gracegoo-stripe** [stripe/vscode-stripe#247]
When clicking on logs today, it takes you to the page on the dashboard. What we want is to be able to click on the log entry and have it open in a new tab, like the events.

**Comment by vcheung-stripe** [comment]
TODO:
- [ ] CLI should return log details via gRPC.
- [ ] Logs streaming UI should be updated to use gRPC instead of stdout.
  - WIP branch: https://github.com/stripe/vscode-stripe/compare/master...vcheung-stripe:vcheung/streaming-views-daemon?expand=1

**Comment by vcheung-stripe** [comment]
For showing log details inside vscode, it turns out there are technical limitations that make it difficult to show *requests*. On the other hand, *responses* are easy to show. Estimating cost of various options:
1. Show only error responses (very easy; est. 1 day)
1. Show responses for both errors and non-errors (easy; est. couple days)
1. Show requests and responses (very hard; est. multiple weeks)

I think option 3 is too hard, and option 2 would be weird (there's responses but no requests). I propose a tradeoff where we take option 1 and do this:
- show basic log details in the vscode editor [0]
- if there's an error, show the error [1]
- in either case, render an inline link on the `request_id` field, which allows a user to click into the dashboard to view the log (not pictured)

What are your thoughts @jbyrum-stripe @gracegoo-stripe @ctrudeau-stripe? 

[0] ![Screen Shot 2021-06-07 at 2 14 49 PM](https://user-images.githubusercontent.com/71457708/121088562-c80b3200-c79a-11eb-9732-d1e8c9138003.png)

[1] ![Screen Shot 2021-06-07 at 2 14 27 PM](https://user-images.githubusercontent.com/71457708/121088564-c93c5f00-c79a-11eb-948d-78f0154969e9.png)

**Comment by jbyrum-stripe** [comment]
Thanks Vincent --

- What are some of the technical limitations that make it hard to show requests?
- Would the View panel still show the request info?  For example, `[200] POST /v1/refunds [req_id]`
- Based on your writeup, I didn't understand whether a user would still see the response body from a `200`.  Screenshot [0] suggests "yes", but I want to confirm

**Comment by vcheung-stripe** [comment]
@jbyrum-stripe 
- The technical limitation is that this is problem where two streams of data (requests, responses) need to be paired up. Some risky backend changes would have to be made to the CLI logs tail feature -- risky in terms of increased storage/memory pressure, increased latency, and reduced reliability for delivering logs to the CLI. It's certainly doable, but it's not a trivial problem. I don't want to leak any more of the architecture, so I'm happy to chat offline.
- Yes, the View panel would still show the info as you describe.
- A user would NOT see the response body from a `200`.

**Comment by jbyrum-stripe** [comment]
Why would we want to only show the response body from non 200s?  That's inconsistent with the Dashboard, no?

**Comment by vcheung-stripe** [comment]
The CLI logs tail feature has historically only shown the response body from non-200s. Yes, this is inconsistent with the Dashboard.

**Comment by tomer-stripe** [comment]
@jbyrum-stripe at the time we were planning to do livemode log streaming too and did not want to expose PII data through the CLI . Since then we decided to focus on testmode only but we never revisited exposing more data (we hadn't heard any user requests about it). If we add more fields we'd likely need to circle back with the security/privacy teams on this.

**Comment by vcheung-stripe** [comment]
@jbyrum-stripe Is it worth the cost to include requests and responses? Or is this solution okay? https://github.com/stripe/vscode-stripe/issues/247#issuecomment-856275941

**Comment by jbyrum-stripe** [comment]
@vcheung-stripe Let's go with your solution, because I don't think we will get a strong sense for how it feels until we try it. 
How quickly can we implement and play with it?

**Comment by vcheung-stripe** [comment]
@jbyrum-stripe I can have something by EOD today.

**Comment by jbyrum-stripe** [comment]
@vcheung-stripe I played with this this morning, and it looked good to me.

Is it possible to pull this information into the detail view?

<img width="739" alt="Screen Shot 2021-06-10 at 7 52 09 AM" src="https://user-images.githubusercontent.com/76178996/121547325-e5b9e080-c9c0-11eb-89bb-f08e91f4d8c8.png">

If not, let's ship this.

**Comment by vcheung-stripe** [comment]
It's not possible to show these messages currently, but there's been discussion around enabling the CLI to receive these messages. If that gets implemented, then showing these messages in VS Code is possible.
