### ISSUE TITLE
[WIP] Add ability to create and execute Stripe fixtures

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/vscode-stripe#25]
**Scenario:**
User wants to create and execute Stripe fixtures. Maybe from an existing event? And to be able to customize the data emitted.

**Create fixtures**
1. In the event tree view, we could add new context menu items so a context menu would show:
 `Trigger this event again` 
 `Create fixture from event`
1. User clicks on  `Trigger this event again`  => `stripe trigger <eventname` gets run
1. User clicks on `Create fixture from event`
1. VS Code grabs the matching fixture from https://github.com/stripe/stripe-cli/tree/master/triggers
1. Stores the content in a new file inside the workspace: `./.stripe/fixtures/<event name.json`
1. Opens a new editor with `./.stripe/fixtures/<event name.json`

How to execute fixtures?
1. Option 1:  New command to execute current open file as fixture?
1. Option 2: New list of fixtures in a view or something and right click option to execute?

**Comment by jbyrum-stripe** [comment]
Related (but not perfectly related) feedback from user feedback:

"it would be super cool to have something like "send new subscription created with a card sucessfully via connect" or "new subscription payment is about to be charged" or "new payment was charged successfully" - so that it delivers all the events as they would normally come. even cooler would be to be able to specify some basic params for these event-chains, e.g. stripe customer id for the  "new subscription payment is about to be charged" or stripe subscription id for the "new subscription payment is about to be charged"."

**Comment by etsai-stripe** [comment]
feature released in v2.0.8
https://jira.corp.stripe.com/browse/DX-6881
