### ISSUE TITLE
Stripe CLI for windows

### ISSUE THREAD

**Issue by camilletasiii** [stripe/vscode-stripe#418]
Hi the stripe exe file when run just open for few seconds and 
![Screenshot 2021-11-07 161927](https://user-images.githubusercontent.com/93859234/140638516-b6947324-be40-4e02-9df0-b97c0038769b.jpg)
 then what 
![image](https://user-images.githubusercontent.com/93859234/140638598-fb0c8cb0-6dee-4db6-9808-35abf864a866.png) 
![image](https://user-images.githubusercontent.com/93859234/140638619-a690c6d6-9f09-4941-b496-c18d8a382353.png)

im using windows and tryimg  to install stripe cli but something is wrong or missing

**Comment by etsai-stripe** [comment]
@camilletasiii could you please try again with v2.0.10

**Comment by mohamednaleem** [comment]
I am facing the same issue by using the windows installation. Tried this  v2.0.10 also. Please help on this

**Comment by etsai-stripe** [comment]
@mohamednaleem 
if you are asking about how to use the stripe CLI, the stripe cli is a tool that can be executed by command line. please see examples at https://stripe.com/docs/api/request_ids?lang=cli and CLI docs at https://stripe.com/docs/stripe-cli

stripe for vscode extension prompts to install stripe CLI because the vscode extension runs CLI command/services in the background.
