### ISSUE TITLE
Trigger events command should list recently used event names in dropdown

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/vscode-stripe#77]
Trigger events command should list recently used event names in dropdown, so they appear on the top.

**Comment by vcheung-stripe** [comment]
Here's a thought for UX: the "recently triggered" events in the dropdown should be the ones that the user triggered from clicking **Trigger new event**, rather than events created by manually typing `stripe trigger` or by other members of the account. However, there's a concern that the **Recent events** list will be confusing, since it shows _all_ the events in the account. Do you have any thoughts on this @auchenberg-stripe?

**Comment by pepin-stripe** [comment]
If I may randomly chime in;
1. To me the clock icon is pretty explicit on communicating that it's recent events (but indeed can't more _more_ explicit than text, so both work for me)
2. How are events "in the account" split? Is it really for "the whole account" or can we at least filter events per api key? AFAIK we generate a CLI-specific key for each instance of the CLI, so if we can filter by key we could potentially load all events triggered by the same user (machine), and show both the ones triggered from VSCode and the ones from the CLI directly. That would be ideal because I could see users using both CLI and VSCode extension.

**Comment by gracegoo-stripe** [comment]
I chatted with Pepin offline (thanks, pepin!). To summarize our discussion:
1. There does not seem to be a way to send the API key as a parameter to filter events server-side.
2. There isn't data returned in the events blob that would let us do so client-side as far as I can tell.

So I'll continue exploring Vincent's suggestion where the UX is to only show the events triggered within VSCode. There's one open question that still remains: Should the events under the "Recent Events" view be generated with the same logic? Or remain as is?

**Comment by auchenberg-stripe** [comment]
Quick feedback:

1) Makes a lot of sense to align "recently used events" to those who have been triggered from within VS Code. This aligns well with how VS Code works for recently used commands, projects, and alike.

2) Recent events lists events from coming Stripe, and should list everything from the given account (how it works today). 

To me the conceptual difference between the two are source. Is the data source local or remote? Recency should align to that.

**Comment by gracegoo-stripe** [comment]
Thanks for the input, Kenneth. We should be good to close this one out then!
